"""Updated Payment model

Revision ID: 3ab6edc7cf76
Revises: 3f0b84e23fa5
Create Date: 2025-02-25 23:18:42.535003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab6edc7cf76'
down_revision = '3f0b84e23fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
