"""Updated Payment model

Revision ID: 3f0b84e23fa5
Revises: 9cb7368798d9
Create Date: 2025-02-25 23:18:09.514700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f0b84e23fa5'
down_revision = '9cb7368798d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('item_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('transaction_amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    # ### end Alembic commands ###
