"""Updated Payment model

Revision ID: 9cb7368798d9
Revises: b13b68b03fa8
Create Date: 2025-02-25 22:58:34.641014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9cb7368798d9'
down_revision = 'b13b68b03fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint('payment_ibfk_1', type_='foreignkey')
        batch_op.drop_column('restaurant_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('payment_ibfk_1', 'restaurant', ['restaurant_id'], ['id'])

    # ### end Alembic commands ###
